---
- name: Install datadog dependencies
  apt: name={{item}} state=present
  with_items:
    - sysstat

- name: Compile datadog
  shell: |
    DD_START_AGENT=0 DD_API_KEY={{ datadog_api_key }} sh -c \
    "$(curl -L https://raw.githubusercontent.com/DataDog/dd-agent/master/packaging/datadog-agent/source/setup_agent.sh)"
  args:
    creates: /root/.datadog-agent
  variables:
    

- name: Add datadog systemd service
  template:
    src: files/datadog.service.j2
    dest: /etc/systemd/system/datadog.service

- name: Reload service files
  systemd:
    daemon_reload: true

- name: Enable and start datadog agent
  service:
    name: datadog.service
    state: restarted
    enabled: true
