---
- hosts: all
  tasks:
  - name: ensure apt cache is up to date
    apt:
      update_cache: "yes"
      cache_valid_time: 3600
      force_apt_get: "yes"
    become: "yes"

- hosts: all
  gather_facts: no
  become: true
  roles:
    - { name: ansible-common, tags: common }
    - { name: ansible-os-hardening, tags: hardening }
    - { name: ansible-ssh-hardening, tags: hardening }
  vars_files:
    - "environments/{{ env }}/group_vars/common/vars.yml"

- hosts: smtp
  gather_facts: no
  become: true
  roles:
    - { name: smtp, tags: smtp }
  vars_files:
    - "environments/{{ env }}/group_vars/smtp/vars.yml"
    - "environments/{{ env }}/group_vars/smtp/vault.yml"

- hosts: load-balancer
  gather_facts: no
  become: true
  roles:
    - name: load-balancer
      tags: load-balancer
    - name: ansible-nginx-hardening
      tags: load-balancer

- hosts: monit
  gather_facts: no
  become: true
  vars_files:
    - "environments/{{ env }}/group_vars/monit/vars.yml"
  handlers:
    - import_tasks: roles/load-balancer/handlers/main.yml
  roles:
    - { name: monit, tags: monit }

- hosts: backup
  gather_facts: no
  become: yes
  handlers:
    - import_tasks: roles/monit/handlers/main.yml
  roles:
    - { name: backup, tags: backup }

- hosts: database
  gather_facts: no
  become: "yes"
  vars_files:
    - "environments/{{ env }}/group_vars/database/vars.yml"
  roles:
    - name: create-mount
      tags: database
    - role: geerlingguy.postgresql
      tags: database
  handlers:
    - import_tasks: roles/monit/handlers/main.yml

- hosts: python3
  gather_facts: no
  roles:
    - { name: smehan.compile-python3, tags: python3, become: yes }
  vars:
    - compiled_python_version: 3.7.0

- hosts: stocks
  gather_facts: no
  vars_files:
    - "environments/{{ env }}/group_vars/stocks/vars.yml"
    - "environments/{{ env }}/group_vars/stocks/vault.yml"
  roles:
    - { name: django, tags: stocks }
  handlers:
    - import_tasks: roles/load-balancer/handlers/main.yml
    - import_tasks: roles/monit/handlers/main.yml