---
- name: Destroy on OpenStack
  hosts: openstack
  tasks:
    - name: detach volume
      os_server_volume:
        state: absent
        server: "{{ infra_env }}_server"
        volume: database_volume
    - name: Detach floating ip
      os_floating_ip:
        state: absent
        floating_ip_address: "{{ floating_ip }}"
        server: "{{ infra_env }}_server"
        wait: yes
    - name: Destroy instance
      os_server:
        state: absent
        name: "{{ infra_env }}_server"
        wait: yes
    - name: Destroy router
      os_router:
        state: absent
        name: "{{ infra_env }}_router"
        wait: yes
#    - name: Destroy subnet
#      os_subnet:
#        state: absent
#        name: "{{ infra_env }}_subnet"
#        wait: yes
#    - name: Destroy network
#      os_network:
#        state: absent
#        name: "{{ infra_env }}_network"
#        wait: yes
