---
- hosts: database
  roles:
    - { name: common, tags: common }
    - { name: database, tags: database }
- hosts: concourse-web
  roles:
    - { name: common, tags: common }
    - { name: concourse-web, tags: concourse-web }
- hosts: vogelsangh-beta
  roles:
    - { name: common, tags: common }
    - { name: vogelsangh, tags: vogelsangh-beta, vogelsangh_env: "beta" }
