---
- hosts: all
  become: true
  roles:
    - { name: common, tags: common }
- hosts: database
  become: true
  roles:
    - { name: database, tags: database }
- hosts: load-balancer
  become: true
  roles:
    - { name: load-balancer, tags: load-balancer }
#- hosts: concourse-web
#  roles:
#    - { name: common, tags: common }
#    - { name: concourse-web, tags: concourse-web }
#- hosts: vogelsangh-beta
#  vars_files:
#    - "environments/{{ env }}/group_vars/vogelsangh-beta/vars.yml"
#    - "environments/{{ env }}/group_vars/vogelsangh-beta/vault.yml"
#  roles:
#    - { name: django, tags: vogelsangh-beta }
#- hosts: loo
#  vars_files:
#    - "environments/{{ env }}/group_vars/loo/vars.yml"
#    - "environments/{{ env }}/group_vars/loo/vault.yml"
#  roles:
#    - { name: django, tags: loo }
- hosts: stocks
  vars_files:
    - "environments/{{ env }}/group_vars/stocks/vars.yml"
#    - "environments/{{ env }}/group_vars/stocks/vault.yml"
  roles:
    - { name: django, tags: stocks }
