---
- hosts: database
  roles:
    - { name: common, tags: common }
    - { name: database, tags: database }
- hosts: concourse-web
  roles:
    - { name: common, tags: common }
    - { name: concourse-web, tags: concourse-web }
- hosts: vogelsangh-beta
  roles:
    - { name: common, tags: common }
    - { name: load-balancer, tags: load-balancer }
    - { name: django, tags: vogelsangh-beta }
