---
- name: Deploy on OpenStack
  hosts: openstack
  gather_facts: false
  tasks:
    - name: Add Ansible keypair
      os_keypair:
        state: present
        name: ansible
        public_key_file: /Users/geertweggemans/.ssh/ansible.pub

    - name: Configure network
      os_network:
        state: present
        availability_zone: NL1
        name: "{{ env }}_network"
        external: false
        shared: false
        wait: true

    - name: Configure subnet
      os_subnet:
        state: present
        availability_zone: NL1
        network_name: "{{ env }}_network"
        name: "{{ env }}_subnet"
        cidr: 10.166.28.0/24
        gateway_ip: 10.166.28.1
        enable_dhcp: true
        dns_nameservers:
          - 194.60.207.52
          - 194.60.207.53

    - name: Configure router
      os_router:
        state: present
        availability_zone: NL1
        name: "{{ env }}_router"
        enable_snat: true
        network: net-public
        interfaces:
          - "{{ env }}_subnet"
        wait: true

    - name: Deploy an instance
      os_server:
        state: present
        availability_zone: NL1
        name: "{{ env }}_server"
        image: CloudVPS Debian 8
        key_name: ansible
        flavor: Standard 1
        security_groups:
          - built-in-allow-icmp
          - built-in-allow-web
          - built-in-provider-access
          - built-in-remote-access
        network: "{{ env }}_network"
        floating_ips:
          - "{{ floating_ip }}"
        meta:
          hostname: "{{ host_name }}"
        wait: true

    - name: configure a 8gb database volume
      os_volume:
        state: present
        availability_zone: NL1
        size: 8
        display_name: database_volume
        wait: true

    - name: attach database volume to host
      os_server_volume:
        state: present
        server: "{{ env }}_server"
        volume: database_volume
        device: /dev/vdb

    - name: configure a 8gb backup volume
      os_volume:
        state: present
        availability_zone: NL1
        size: 8
        display_name: backup_volume
        wait: true

    - name: attach backup volume to host
      os_server_volume:
        state: present
        server: "{{ env }}_server"
        volume: backup_volume
        device: /dev/vdc
