---
- src: https://github.com/roadmanict/ansible-common.git
  version: v0.1.2
- dev-sec.os-hardening
- dev-sec.ssh-hardening
- src: https://github.com/dev-sec/ansible-nginx-hardening
  version: master
- smehan.compile-python3