---
- src: https://github.com/roadmanict/ansible-common.git
  version: v0.1.1
- src: https://github.com/dev-sec/ansible-os-hardening
  version: 4.3.0
- src: https://github.com/dev-sec/ansible-ssh-hardening
  version: 4.4.0
- src: https://github.com/dev-sec/ansible-nginx-hardening
  version: 1.0.2