---
- name: ensure apt cache is up to date
  apt: update_cache=yes cache_valid_time=3600
- name: ensure packages are installed
  apt: name={{item}} state=present
  with_items:
    - monit
- name: Copy monit config
  template:
    src: files/monitrc
    dest: /etc/monit/monitrc
  notify: restart monit
- name: Copy nginx config
  template:
    src: files/nginx.conf.j2
    dest: /etc/nginx/sites-enabled/monit.conf
  notify: reload nginx
