---
- import_tasks: install.yml
  become: true

- import_tasks: request-cert.yml
  become: true
  tags:
    - certbot
  when: env != "vagrant"

- import_tasks: vagrant.yml
  become: true
  tags:
    - certbot
  when: env == "vagrant"
