---
- name: Copy nginx config
  template:
    src: files/nginx.conf.j2
    dest: "/etc/nginx/sites-enabled/certbot-{{ project_name }}.conf"
  notify: reload nginx

- name: Check if certificate exists
  stat:
    path: '{{ certbot_root }}/{{ project_name }}'
  register: cert_dir

- name: Create certbot directory
  file:
    path: "{{ certbot_root }}/{{ project_name }}"
    state: directory
    mode: 0755
    owner: www-data
    group: www-data
  when: cert_dir.stat.isdir is undefined

- name: create certbot certificates
  shell: |
    certbot certonly --webroot -w {{ certbot_root }}/{{ project_name }} \
      --agree-tos --keep -d {{ item }} --email {{ email }}
  with_items:
    "{{ domains }}"
  when: cert_dir.stat.isdir is undefined
