---
project_domain: stocks.roadman.nl
project_name: "stocks"
django_name: "stocks"
project_repository: git@bitbucket.org:roadman/stocks.git
project_gunicorn_port: 8020
django_systemd_services:
  - name: binance
    command: manage.py binance
django_default_branch: master
django_db_host: 192.168.2.31