---
project_domain: stocks.roadman.nl
project_name: "stocks"
django_name: "stocks"
project_repository: git@bitbucket.org:roadman/stocks.git
project_gunicorn_port: 8020
django_cron_jobs:
- name: Stocks Database backup
  user: postgres
  weekday: "*"
  minute: 0
  hour: 2
  job: "pg_dump -Fc {{ django_db_name }} > {{ backup_dir }}/database/$(date -u +\\%Y\\%m\\%dT\\%H\\%M\\%S)_{{ project_name }}_database_backup.tar"
  file: stocks_database_backup
  state: present
django_systemd_services:
  - name: binance
    command: manage.py binance
django_default_branch: master
django_db_host: 192.168.2.31