---
- name: ensure to listen to Docker ip address ranges
  lineinfile:
    dest: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
    regexp: '^listen_addresses'
    insertafter: '^#listen_addresses '
    line: "listen_addresses 'localhost, 172.17.0.1'"

- name: ensure to listen to Docker ip address ranges
  lineinfile:
    dest: "/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf"
    regexp: '^host all all 172.17.0.0/16 md5'
    line: "host all all 172.17.0.0/16 md5"

- name: Copy conf files to postgres data directory
  copy:
    remote_src: True
    src: "/etc/postgresql/{{ postgresql_version }}/main/{{ item }}"
    dest: "/var/lib/postgresql/{{ postgresql_version }}/main/{{ item }}"
  with_items:
    - pg_ctl.conf
    - postgresql.conf
    - pg_hba.conf
    - pg_ident.conf
    - start.conf

- name: restart postgresql
  service: name=postgresql state=restarted