---
- name: ensure database volume is formatted
  filesystem:
    fstype: ext4
    dev: "{{ database_drive_device }}"

- name: automount volume
  mount:
    boot: yes
    state: mounted
    fstype: ext4
    src: "{{ database_drive_device }}"
    name: /var/lib/postgresql