---
- name: Copy systemd concourse-worker template
  template:
    src: files/concourse-worker.service.j2
    dest: /etc/systemd/system/concourse-worker.service
- name: Creates concourse ssh-key worker directory
  file: path=/usr/lib/concourse/keys/worker state=directory
- name: Generate worker_key SSH key
  shell: ssh-keygen -t rsa -f /usr/lib/concourse/keys/worker/worker_key -N ""
  args:
    creates: /usr/lib/concourse/keys/worker/worker_key
- name: enable concourse-worker
  systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: concourse-worker