---
- name: Copy systemd concourse-web template
  template:
    src: files/concourse-web.service.j2
    dest: /etc/systemd/system/concourse-web.service
- name: Creates concourse ssh-key web directory
  file: path=/usr/lib/concourse/keys/web state=directory
- name: Generate tsa_host_key SSH key
  shell: ssh-keygen -t rsa -f /usr/lib/concourse/keys/web/tsa_host_key -N ""
  args:
    creates: /usr/lib/concourse/keys/web/tsa_host_key
- name: Generate session_signing_key SSH key
  shell: ssh-keygen -t rsa -f /usr/lib/concourse/keys/web/session_signing_key -N ""
  args:
    creates: /usr/lib/concourse/keys/web/session_signing_key
- name: enable concourse-web
  systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: concourse-web
