---
- include: dependencies.yml
- include: database.yml
  become: yes
  become_user: postgres

- include: concourse-web.yml
- include: concourse-worker.yml

- name: Copy files worker key to authorized worker keys
  copy: remote_src=True src=/usr/lib/concourse/keys/worker/worker_key.pub dest=/usr/lib/concourse/keys/web/authorized_worker_keys
- name: Copy files tsa_host_key to worker
  copy: remote_src=True src=/usr/lib/concourse/keys/web/tsa_host_key.pub dest=/usr/lib/concourse/keys/worker
- name: Copy nginx configuration
  template:
    src: files/nginx.conf.j2
    dest: /etc/nginx/sites-enabled/concourse.conf
- name: reload nginx
  service: name=nginx state=reloaded