---
#- name: ensure backup volume is formatted
#  filesystem:
#    fstype: ext4
#    dev: "{{ backup_volume }}"

- name: automount volume
  mount:
    boot: yes
    state: mounted
    fstype: ext4
    src: "UUID={{ backup_volume }}"
    name: "{{ backup_dir }}"