---
- name: ensure apt cache is up to date
  apt: update_cache=yes cache_valid_time=3600

- name: ensure packages are installed
  apt: name={{item}} state=present
  with_items:
  - python-swiftclient

- name: copy swift rc file
  template:
    src: files/swift_rc.sh
    dest: /root

- name: add cronjob to backup to openstack
  cron:
    name: upload backup to the object store
    minute: 0
    hour: 3
    job: swift upload --changed berry_backup /tmp/backup
    state: present

- name: Add to monit
  template:
    src: files/monit.j2
    dest: /etc/monit/conf.d/backup
  notify: reload monit
