---
- name: ensure packages are installed
  apt: name={{item}} state=present
  with_items:
  - python-swiftclient

- name: copy swift rc file
  template:
    src: files/swift_rc.sh
    dest: "/home/{{ ansible_user_id }}"

- name: add cronjob to backup to openstack
  cron:
    name: upload backup to the object store
    minute: 0
    hour: 3
    job: "bash --rcfile /home/{{ ansible_user_id }}/swift_rc.sh -ci \"swift upload --changed berry_backup {{ backup_dir }}\""
    state: present
    cron_file: backup_to_openstack
    user: "{{ ansible_user_id }}"

- name: add ssh backup key to user
  become: "no"
  copy:
    src: "environments/{{ env }}/files/backup_key"
    dest: "~/.ssh/backup_key"
    mode: 0600

- name: chown backup dir
  file:
    path: "{{ backup_dir }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: 0755
    recurse: "yes"