---
project_domain: stocks.gweggemans.local
project_name: "stocks"
django_name: "stocks"
project_repository: git@bitbucket.org:roadman/stocks.git
project_gunicorn_port: 8200
django_cron_jobs:
- name: Stocks Database backup
  user: postgres
  weekday: "*"
  minute: 53
  hour: "*"
  job: "pg_dump -Fc {{ django_db_name }} > /tmp/{{ project_name }}_database_backup.tar"
  file: stocks_database_backup
  state: present
django_systemd_services:
  - name: binance
    command: manage.py binance
django_default_branch: production