---
- name: ensure apt cache is up to date
  apt: update_cache=yes cache_valid_time=3600
- name: install python3
  apt: name={{item}} state=present
  with_items:
  - python3
  - python3-pip
  - python3-venv
- name: create user
  user:
    name: "vogelsangh_{{ vogelsangh_env }}"
    state: present
