---
- include: configure.yml
- include: database.yml
  become: yes
  become_user: postgres
- include: install.yml
  become: yes
  become_user: "vogelsangh_{{ vogelsangh_env }}"
  environment:
    VOGELSANGH_ENV: "{{ vogelsangh_env }}"
    DJANGO_SETTINGS_MODULE: vogelsangh.settings.production