---
- name: ensure apt cache is up to date
  apt: update_cache=yes cache_valid_time=3600
- name: ensure dependencies are installed
  apt: name={{item}} state=present
  with_items:
  - nginx
#- name: Add default configuration for nginx
#  copy: src=default.conf dest=/etc/nginx/sites-enabled/_.conf
#- name: Restart nginx
#  service: name=nginx state=reloaded