---
- name: Restart django project
  service:
    name: "{{ project_name }}"
    state: restarted
    enabled: true
  become: "yes"

- name: Restart django custom systemd files
  service:
    name: "{{ project_name }}_{{ item.name }}"
    state: restarted
    enabled: false
  with_items: "{{ django_systemd_services }}"
  become: "yes"
