---
project_domain: beta.vogelsangh-dwingeloo.nl
project_name: "vogelsangh"
project_env: beta
project_repository: https://github.com/roadmanict/vogelsangh.git
project_gunicorn_port: 8000
tls_enabled: false