---
- name: ensure apt cache is up to date
  apt: update_cache=yes cache_valid_time=3600

- name: install python packages
  apt: name={{item}} state=present
  with_items:
  - nginx
  - python3
  - python3-pip
  - python3-venv
  - python3-dev
  - build-essential
  - libssl-dev
  - libffi-dev
  - software-properties-common
  - libatlas3-base

- name: create user
  user:
    name: "{{ django_user }}"
    state: present

- name: Create media directory
  file:
    path: "{{ django_media_dir }}"
    state: directory
    mode: 0755
    owner: "{{ django_user }}"
    group: www-data

- name: Copy systemd file
  template:
    src: files/django.service.j2
    dest: "/etc/systemd/system/{{ project_name }}.service"

- name: Copy custom systemd files
  template:
    src: files/django_custom.service.j2
    dest: "/etc/systemd/system/{{ project_name }}_{{ item.name }}.service"
  with_items: "{{ django_systemd_services }}"

- name: Reload service files
  systemd:
    daemon_reload: yes

- name: Copy nginx config
  template:
    src: files/nginx.conf.j2
    dest: "/etc/nginx/sites-enabled/{{ project_name }}.conf"
  notify: reload nginx
#
- name: Add project to monit
  template:
    src: files/monit.j2
    dest: "/etc/monit/conf.d/{{ project_name }}.conf"
  notify: restart monit
  vars:
    systemd_services: "{{ django_systemd_services }}"
  tags:
    - monit