---
- name: Ensure .ssh directory exists
  file: path=~/.ssh state=directory mode=0700

- name: add deploy key to user
  copy:
    src: "environments/{{ env }}/files/deploy_key"
    dest: "~/.ssh/deploy_key"
    mode: 0600

- name: checkout repository
  git:
    repo: "{{ project_repository }}"
    dest: "{{ django_project_root }}"
    key_file: ~/.ssh/deploy_key
    accept_hostkey: yes
    version: "{{ django_default_branch }}"

- name: Install project dependencies
  pip:
    requirements: "{{ django_project_root }}/prod_requirements.txt"
    virtualenv: "{{ django_venv_dir }}"
    virtualenv_command: "pyvenv-3.5"

- name: Copy local settings
  template:
    src: files/local_settings.py.j2
    dest: "{{ django_project_root }}/{{ django_name }}/settings/local.py"

- name: Copy gunicorn configuration
  template:
    src: files/gunicorn.conf.py.j2
    dest: "{{ django_project_root }}/gunicorn.conf.py"

- name: Make sure log files exist
  copy:
    content: ""
    dest: "{{ django_project_root }}/{{ item }}.log"
    force: no
  with_items:
    - error
    - access

- name: Run django manage commands
  django_manage:
    command: "{{ item }}"
    app_path: "{{ django_project_root }}"
    virtualenv: "{{ django_venv_dir }}"
  with_items:
    - migrate
    - collectstatic