---
- name: Fix django static permissions
  file: path="{{ django_static_dir }}" owner="{{ django_user }}" group=www-data mode=0775 state=directory recurse=yes

- name: Enable and start gunicorn
  service:
    name: "{{ project_name }}"
    state: restarted
    enabled: yes

- name: Enable custom systemd files
  service:
    name: "{{ project_name }}_{{ item.name }}"
    state: restarted
    enabled: yes
  with_items: "{{ django_systemd_services }}"

- name: Restart nginx
  service: name=nginx state=reloaded

- cron:
    name: "{{ item.name }}"
    weekday: "{{ item.weekday }}"
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
    user: "{{ item.user }}"
    job: "{{ item.job }}"
    cron_file: "{{ item.file }}"
    state: "{{ item.state }}"
  with_items: "{{ django_cron_jobs | default([]) }}"