---
- import_tasks: configure.yml
  become: yes

- import_tasks: database.yml
  become: yes
  become_user: postgres

- import_tasks: deploy.yml
  become: yes
  become_user: "{{ django_user }}"
  environment:
    DJANGO_SETTINGS_MODULE: "{{ django_name }}.settings.production"
  tags:
   - deploy

- import_tasks: enable.yml
  become: yes
  tags:
   - deploy