---
- import_tasks: configure.yml
  become: true

- import_tasks: deploy.yml
  become: true
  become_user: "{{ django_user }}"
  environment:
    DJANGO_SETTINGS_MODULE: "{{ django_name }}.settings.production"
  tags:
    - deploy

- import_tasks: enable.yml
  become: true
  tags:
    - deploy
