---
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: set hostname in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: ^127.0.1.1
    line: "127.0.1.1 {{ inventory_hostname }}"