---
- name: Update /etc/hostname file
  copy:
    content: '{{inventory_hostname}}'
    dest: /etc/hostname
    force: no
  notify: reset hostname

- name: set hostname in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: ^127.0.1.1
    line: "127.0.1.1 {{ inventory_hostname }}"