---
- import_tasks: bootstrap.yml
  become: yes

- import_tasks: upgrade.yml
  become: yes

- import_tasks: hostname.yml
  become: yes

- import_tasks: authorized_keys.yml
  become: yes

- import_tasks: backup_volume.yml
  become: yes
  when: backup_volume is defined