---
- name: Set authorized key took from file
  authorized_key:
    user: "{{ ansible_user | default('root') }}"
    state: present
    key: "{{ item }}"
  with_items: "{{ ssh_keys }}"

- name: Disable password login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication no$"
    line: "PasswordAuthentication no"
    state: present
  notify: reload ssh