---
- hosts: vps64810.roadmanict.nl
  remote_user: deploy
  vars:
    required_packages:
     - monit
     - nginx
    required_packages_backports:
     - certbot
  tasks:
   - name: configure jessie backports
     apt_repository: repo='deb http://ftp.debian.org/debian jessie-backports main' state=present
     become: yes
     become_method: sudo
   - name: Update APT package cache
     apt: update_cache=yes cache_valid_time=3600
     become: yes
     become_method: sudo
   - name: Install required packages
     apt: state=installed pkg={{ item }}
     with_items: '{{required_packages}}'
     become: yes
     become_method: sudo
   - name: install certbot
     apt: name=certbot state=present default_release=jessie-backports
     become: yes
     become_method: sudo

   - name: Enable and start nginx
     service: name=nginx state=started enabled=yes
     become: yes
     become_method: sudo
   - name: Enable and start monit
     service: name=monit state=restarted enabled=yes
     become: yes
     become_method: sudo
   - name: ufw allow http
     ufw: rule=allow port=http proto=tcp
     become: yes
     become_method: sudo
     notify: Restart ufw
   - name: ufw allow https
     ufw: rule=allow port=https proto=tcp
     become: yes
     become_method: sudo
     notify: Restart ufw

   - name: create certbot certificates
     shell: 'certbot certonly -n --agree-tos --keep --standalone -d monit.roadmanict.nl --email geert@gweggemans.nl'
     become: yes
     become_method: sudo
  
   - name: Add deploy user to sudoers
     lineinfile: dest=/etc/monit/monitrc
                 regexp="{{item.regexp}}"
                 line="{{item.line}}"
                 state=present
     with_items:
      - { regexp: '#?\s*set httpd port 2812 and', line: 'set httpd port 2812 and' }
      - { regexp: '#?\s*use address localhost', line: '    use address localhost' }
      - { regexp: '#?\s*allow [a-z]*:[a-z]*', line: '    allow geert:arrowned' }
     become: yes
     become_method: sudo
   - name: Add monitrc.d files
     copy: src={{item.src}} dest={{item.dest}}
     become: yes
     become_method: sudo
     with_items:
      - { src: 'src/monitrc.d/cron', dest: '/etc/monit/conf.d/cron'}
      - { src: 'src/monitrc.d/nginx', dest: '/etc/monit/conf.d/nginx'}
      - { src: 'src/monitrc.d/openssh-server', dest: '/etc/monit/conf.d/openssh-server'}
      - { src: 'src/monitrc.d/postfix', dest: '/etc/monit/conf.d/postfix'}
      - { src: 'src/monitrc.d/rsyslog', dest: '/etc/monit/conf.d/rsyslog'}
   - name: Reload monit
     service: name=monit state=reloaded
     become: yes
     become_method: sudo
   - name: add monit to nginx
     copy: src=src/nginx/monit.conf dest=/etc/nginx/sites-enabled/monit.conf
     become: yes
     become_method: sudo
     notify: Reload nginx

  handlers:
   - name: Restart ufw
     service: name=ufw state=restarted
     become: yes
     become_method: sudo
   - name: Reload nginx
     service: name=nginx state=reloaded
     become: yes
     become_method: sudo