---
mount_device_uuid: UUID=1acf08f8-41c0-4a70-9309-a527f9b1a113
mount_location: /var/lib/postgresql
postgresql_hba_entries:
  - { type: local, database: all, user: postgres, auth_method: peer }
  - { type: local, database: all, user: all, auth_method: peer }
  - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5 }
  - { type: host, database: all, user: all, address: '::1/128', auth_method: md5 }
  - { type: host, database: all, user: all, address: '192.168.2.0/24', auth_method: md5 }
postgresql_global_config_options:
  - option: listen_addresses
    value: '*'